package models

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

// FeedCardType defines the type of feed card generated by agents or services.
// See FRONTEND_V2_SPEC.md §3
type FeedCardType string

const (
	FeedCardDailyBriefing       FeedCardType = "daily_briefing"
	FeedCardProcurementWarning  FeedCardType = "procurement_warning"
	FeedCardProcurementCritical FeedCardType = "procurement_critical"
	FeedCardTaskStarting        FeedCardType = "task_starting"
	FeedCardTaskCompleted       FeedCardType = "task_completed"
	FeedCardInspectionUpcoming  FeedCardType = "inspection_upcoming"
	FeedCardInspectionResult    FeedCardType = "inspection_result"
	FeedCardScheduleRecalc      FeedCardType = "schedule_recalc"
	FeedCardWeatherRisk         FeedCardType = "weather_risk"
	FeedCardWeatherWindow       FeedCardType = "weather_window"
	FeedCardSubConfirmation     FeedCardType = "sub_confirmation"
	FeedCardSubUnconfirmed      FeedCardType = "sub_unconfirmed"
	FeedCardInvoiceReady        FeedCardType = "invoice_ready"
	FeedCardBudgetAlert         FeedCardType = "budget_alert"
	FeedCardSetupTeam           FeedCardType = "setup_team"
	FeedCardSetupContacts       FeedCardType = "setup_contacts"
	FeedCardCalibrationDrift    FeedCardType = "calibration_drift"
	FeedCardMilestone           FeedCardType = "milestone"
	FeedCardWelcome             FeedCardType = "welcome"

	// Agent approval card types (human-in-the-loop)
	FeedCardAgentApproval    FeedCardType = "agent_approval"       // Agent requests human approval for an action
	FeedCardAgentRecommend   FeedCardType = "agent_recommendation" // Agent recommends action (informational)
	FeedCardChangeOrder      FeedCardType = "change_order"         // Non-standard change requiring approval
	FeedCardDelayMitigation  FeedCardType = "delay_mitigation"     // Delay response options
	FeedCardDraftMessage     FeedCardType = "draft_message"        // Claude-drafted message for review

	// Integration card types (FB-Brain cross-system flows)
	FeedCardMaterialQuotePrompt  FeedCardType = "material_quote_prompt"
	FeedCardMaterialQuoteReview  FeedCardType = "material_quote_review"
	FeedCardMaterialOrderConfirm FeedCardType = "material_order_confirm"
	FeedCardLaborBidPrompt       FeedCardType = "labor_bid_prompt"
	FeedCardLaborBidReview       FeedCardType = "labor_bid_review"
	FeedCardLaborBidConfirm      FeedCardType = "labor_bid_confirm"
	FeedCardDeliveryConfirm      FeedCardType = "delivery_confirm"
)

// FeedCardHorizon defines the temporal grouping of a feed card.
type FeedCardHorizon string

const (
	FeedCardHorizonToday    FeedCardHorizon = "today"
	FeedCardHorizonThisWeek FeedCardHorizon = "this_week"
	FeedCardHorizonHorizon  FeedCardHorizon = "horizon"
)

// FeedCardPriority levels. Lower number = higher priority.
const (
	FeedCardPriorityCritical = 0 // Red — immediate action required
	FeedCardPriorityUrgent   = 1 // Orange — action needed soon
	FeedCardPriorityNormal   = 2 // Blue — informational
	FeedCardPriorityLow      = 3 // Gray — background info
)

// FeedCardAction represents an inline action button on a feed card.
type FeedCardAction struct {
	ID    string `json:"id"`
	Label string `json:"label"`
	Style string `json:"style"` // "primary", "secondary", "danger"
}

// FeedCard represents a single card in the portfolio feed.
// Written by agents, read by the portfolio feed endpoint.
// See FRONTEND_V2_SPEC.md §6.2
type FeedCard struct {
	ID           uuid.UUID        `json:"id" db:"id"`
	OrgID        uuid.UUID        `json:"org_id" db:"org_id"`
	ProjectID    uuid.UUID        `json:"project_id" db:"project_id"`
	CardType     FeedCardType     `json:"card_type" db:"card_type"`
	Priority     int              `json:"priority" db:"priority"`
	Headline     string           `json:"headline" db:"headline"`
	Body         string           `json:"body" db:"body"`
	Consequence  *string          `json:"consequence,omitempty" db:"consequence"`
	Horizon      FeedCardHorizon  `json:"horizon" db:"horizon"`
	Deadline     *time.Time       `json:"deadline,omitempty" db:"deadline"`
	Actions      []FeedCardAction `json:"actions" db:"-"`
	ActionsJSON  []byte           `json:"-" db:"actions"`
	EngineData   json.RawMessage  `json:"engine_data,omitempty" db:"engine_data"`
	AgentSource  *string          `json:"agent_source,omitempty" db:"agent_source"`
	TaskID       *uuid.UUID       `json:"task_id,omitempty" db:"task_id"`
	DismissedAt  *time.Time       `json:"dismissed_at,omitempty" db:"dismissed_at"`
	SnoozedUntil *time.Time       `json:"snoozed_until,omitempty" db:"snoozed_until"`
	CreatedAt    time.Time        `json:"created_at" db:"created_at"`
	ExpiresAt    *time.Time       `json:"expires_at,omitempty" db:"expires_at"`

	// Denormalized for API response (populated by JOIN, not stored)
	ProjectName string `json:"project_name,omitempty" db:"project_name"`
}
